# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://bigdjrp.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: The J Porter
name: Jared R Porter # added for aboutme
tagline: Curious hacker #added for aboutme
description: "Engage"
keywords: 'hacker,hacking tools, penetration, pentester'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/bigdjrp
    - name: instagram
      url:
    - name: linkedin
      url: https://www.linkedin.com/in/jared-porter-9a15a320/
    - name: google
      url: https://plus.google.com/u/0/+JPorterX
    - name: youtube
      url: https://www.youtube.com/channel/UC2tBDRT6DsoCCko6A8gyEYg
    - name: aboutme
      url: https://thejporter.com
home:
  section1: <h1>Welcome</h1>
  section2: <h2>Feel free to have a look at the projects I'm developing</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/bigdjrp" title="View on GitHub"></a></div>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License.
  footer_content: See more of my work here <a href="https://thejporter.com/">TheJPorter</a>.

#-------------added this section for aboutme SIDEBAR------------>
email: jrp4wn@gmail.com
phone: 801 XXX XXXX
website: thejporter.com #do not add http://
linkedin: jared-porter-9a15a320
github: bigdjrp

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_analytics: # e.g. 'UA-42456515-5'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
  about: /
